server:
  port: 9004
spring:
  application:
    name: booking
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookingBD
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:9020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
